#!/bin/sh

LSEP=
LSEPE=
RSEP=
RSEPE=

CLOCK=◷
CALENDAR=☼
MUSIC=♫

WIDTH=${1}

SMALL=80
MEDIUM=140

if [ "$WIDTH" -gt "$MEDIUM" ]; then
  MPD="#[fg=colour154,bg=colour235,nobold,nounderscore,noitalics]$RSEP#[fg=colour232,bg=colour154,nobold,noitalics,nounderscore] $MUSIC  $(currentartist) - $(currenttitle)"
  date_colour='colour252'
fi

if [ "$WIDTH" -ge "$SMALL" ]; then
  UNAME="#[fg=colour154,bg=colour238,nobold,nounderscore,noitalics]$RSEP#[fg=colour232,bg=colour154,noitalics,nounderscore] $(whoami)@$(uname -n)"
fi
DATETIME="#[fg=colour238,bg=colour154,nobold,nounderscore,noitalics]$RSEP#[fg=colour222,bg=colour238] $CALENDAR $(date +'%d/%m/%y') $RSEPE $CLOCK $(date +'%H:%M')"

echo "$MPD $DATETIME $UNAME " | sed 's/ *$/ /g'

